name             'core-bits'
maintainer       'BlackBits'
maintainer_email 'anton@blackbits.pro'
license          'All rights reserved'
description      'configures core things (sshd config, user, zsh, vim, tmux)'
version          '0.1.0'

depends 'apt'
depends 'ssh'
depends 'ntp'
depends 'zsh'
depends 'vim'
depends 'tmux'
depends 'hostname'
